export const skills: string[] = [
  'Java',
  'JavaScript',
  'Python',
  'React.js',
  'Next.js',
  'Node.js',
  'Typescript',
  'Redux',
  'Serverless',
  'Lambdas',
  'DynamoDB',
  'GraphQL',
  'PostgresSQL',
  'Sanity',
  'Gatsby',
  'Cloud Architecture',
  'MicroServices',
  'Amazon Web Services',
  'Nginx',
  'Blockchain(Stellar)',
  'Stripe',
  'HTML5',
  'CSS5',
  'jQuery',
  'CI/CD',
  'Git',
  'GitHub',
  'NPM',
  'YARN',
  'RESTful API',
  'Express',
  'Webpack',
  'ES6',
  'Responsive Design',
  'Scrum framework',
  'Adobe PS & AI'
]